[package]
name = "arch-aarch64"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "AArch64 architecture support for rustboot"

[lib]
name = "arch_aarch64"

[dependencies]
bootcore = { workspace = true }

[features]
default = []
